# Generated by Django 4.1 on 2022-09-02 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(through='reviews_app.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
